# Generated by Django 3.1.4 on 2020-12-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('identifiant', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField()),
                ('mot_de_passe', models.CharField(max_length=32)),
                ('profile', models.CharField(max_length=30)),
            ],
        ),
    ]
